/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mafer
 */
public class GUI extends javax.swing.JFrame {
    
    private Operacion opera;
    private float a; //guardara la estacion en que esta el usuario

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        opera = new Operacion();
        a = 0; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button2 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        textEmisora = new javax.swing.JTextField();
        textEstacion = new javax.swing.JTextField();
        buttonAm = new javax.swing.JButton();
        buttonFm = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonPrev = new javax.swing.JButton();
        buttonOn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setText("2");
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 50, 30));

        button1.setText("1");
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 30));

        button3.setText("3");
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, 30));

        button4.setText("4");
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 50, 30));

        button5.setText("5");
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 50, 30));

        button6.setText("6");
        jPanel1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 50, 30));

        button7.setText("7");
        jPanel1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 30));

        button8.setText("8");
        jPanel1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 50, 30));

        button9.setText("9");
        jPanel1.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 50, 30));

        button10.setText("10");
        jPanel1.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 50, 30));

        button11.setText("11");
        jPanel1.add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 50, 30));

        button12.setText("12");
        jPanel1.add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 440, 130));

        textEmisora.setText("FM");
        getContentPane().add(textEmisora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 30));

        textEstacion.setText("jTextField1");
        getContentPane().add(textEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 320, 30));

        buttonAm.setText("AM");
        getContentPane().add(buttonAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, 40));

        buttonFm.setText("FM");
        getContentPane().add(buttonFm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 40));

        buttonNext.setText("Next");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 90, 40));

        buttonPrev.setText("Anterior");
        buttonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrevActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, 40));

        buttonOn.setText("On/Off");
        getContentPane().add(buttonOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        a = Float.parseFloat(textEstacion.getText());
        float nuevaEstacion = opera.siguiente(a);
        textEstacion.setText(String.valueOf(nuevaEstacion));
        
        
        
        
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrevActionPerformed
         a = Float.parseFloat(textEstacion.getText());
        float nuevaEstacion = opera.anterior(a);
        textEstacion.setText(String.valueOf(nuevaEstacion));
    }//GEN-LAST:event_buttonPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button12;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAm;
    private javax.swing.JButton buttonFm;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonOn;
    private javax.swing.JButton buttonPrev;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textEmisora;
    private javax.swing.JTextField textEstacion;
    // End of variables declaration//GEN-END:variables
}
