/*
Esta clase es la encargada de la GUI. 
Aqui se pondran los botones, textos, etc. todo lo grafico para interactuar con el usuario.
*/

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maria Fernanda Lopez 17160
 * @author Sergio Marchena 16387
 * @since 15/01/2018
 */
public class GUI extends javax.swing.JFrame {
    
    // Atributos
    private Operacion opera;
    private float a; //guardara la estacion en que esta el usuario

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        opera = new Operacion() {};
        a = 0; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        button2 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        textEmisora = new javax.swing.JTextField();
        textEstacion = new javax.swing.JTextField();
        buttonAm = new javax.swing.JButton();
        buttonFm = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonPrev = new javax.swing.JButton();
        buttonOn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        rb11 = new javax.swing.JRadioButton();
        rb12 = new javax.swing.JRadioButton();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setText("2");
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 50, 30));

        button1.setText("1");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 30));

        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, 30));

        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 50, 30));

        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 50, 30));

        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 50, 30));

        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 30));

        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 50, 30));

        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel1.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 50, 30));

        button10.setText("10");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        jPanel1.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 50, 30));

        button11.setText("11");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        jPanel1.add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 50, 30));

        button12.setText("12");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        jPanel1.add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 440, 130));

        textEmisora.setText("FM");
        textEmisora.setEnabled(false);
        getContentPane().add(textEmisora, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 60, 30));

        textEstacion.setEnabled(false);
        textEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEstacionActionPerformed(evt);
            }
        });
        getContentPane().add(textEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 320, 30));

        buttonAm.setText("AM");
        buttonAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAmActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, 40));

        buttonFm.setText("FM");
        buttonFm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFmActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 40));

        buttonNext.setText("Next");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 90, 40));

        buttonPrev.setText("Anterior");
        buttonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrevActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 90, 40));

        buttonOn.setText("On/Off");
        buttonOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOnActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 70, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Guardar emisora"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rb1);
        rb1.setText("1");
        jPanel2.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        buttonGroup1.add(rb2);
        rb2.setText("2");
        jPanel2.add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        buttonGroup1.add(rb3);
        rb3.setText("3");
        jPanel2.add(rb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        buttonGroup1.add(rb4);
        rb4.setText("4");
        jPanel2.add(rb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        buttonGroup1.add(rb5);
        rb5.setText("5");
        jPanel2.add(rb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        buttonGroup1.add(rb6);
        rb6.setText("6");
        jPanel2.add(rb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        buttonGroup1.add(rb7);
        rb7.setText("7");
        jPanel2.add(rb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        buttonGroup1.add(rb8);
        rb8.setText("8");
        jPanel2.add(rb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        buttonGroup1.add(rb9);
        rb9.setText("9");
        jPanel2.add(rb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        buttonGroup1.add(rb10);
        rb10.setText("10");
        jPanel2.add(rb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        buttonGroup1.add(rb11);
        rb11.setText("11");
        jPanel2.add(rb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        buttonGroup1.add(rb12);
        rb12.setText("12");
        jPanel2.add(rb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel2.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 270, 120));

        pack();
    }// </editor-fold>                        

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {                                           
        a = Float.parseFloat(textEstacion.getText());
        float nuevaEstacion = opera.siguiente(a);
        textEstacion.setText(String.valueOf(nuevaEstacion));
              
        
        
    }                                          

    private void buttonPrevActionPerformed(java.awt.event.ActionEvent evt) {                                           
         a = Float.parseFloat(textEstacion.getText());
        float nuevaEstacion = opera.anterior(a);
        textEstacion.setText(String.valueOf(nuevaEstacion));
    }                                          

<<<<<<< HEAD
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       
           textEstacion.setText(String.valueOf(opera.seleccionarFav(1)));
       
    }//GEN-LAST:event_button1ActionPerformed
=======
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
       String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(1)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(13)));
       }
    }                                       
>>>>>>> 8ba1c22f14cca9e9f754a029e09614693f887ac1

    private void button1MousePressed(java.awt.event.MouseEvent evt) {                                     
       
    }                                    

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
    }                                    

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
                
    }                                    

<<<<<<< HEAD
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
     
           textEstacion.setText(String.valueOf(opera.seleccionarFav(2)));
       
    }//GEN-LAST:event_button2ActionPerformed
=======
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
     String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(2)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(14)));
       }
    }                                       
>>>>>>> 8ba1c22f14cca9e9f754a029e09614693f887ac1

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String emi = textEmisora.getText();
        a = Float.parseFloat(textEstacion.getText());
        if (emi.equals("AM")){
            if(rb1.isSelected()){
                int boton = 1;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb2.isSelected()){
                int boton = 2;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito"); 
            } else if(rb3.isSelected()){
                int boton = 3;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb4.isSelected()){
                int boton = 4;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb5.isSelected()){
                int boton = 5;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb6.isSelected()){
                int boton = 6;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb7.isSelected()){
                int boton = 7;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb8.isSelected()){
                int boton = 8;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb9.isSelected()){
                int boton = 9;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb10.isSelected()){
                int boton = 10;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb11.isSelected()){
                int boton = 12;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            }
        } else {
             if(rb1.isSelected()){
                int boton = 1;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb2.isSelected()){
                int boton = 2;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb3.isSelected()){
                int boton = 3;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb4.isSelected()){
                int boton = 4;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb5.isSelected()){
                int boton = 5;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb6.isSelected()){
                int boton = 6;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb7.isSelected()){
                int boton = 7;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb8.isSelected()){
                int boton = 8;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb9.isSelected()){
                int boton = 9;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb10.isSelected()){
                int boton = 10;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb11.isSelected()){
                int boton = 11;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            } else if(rb12.isSelected()){
                int boton = 12;
                opera.guardar(a, boton);
                JOptionPane.showMessageDialog(null, "Se guardo con exito");
            }
            
        }
    }                                       

    private void textEstacionActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        button1.setEnabled(false);
        button2.setEnabled(false);
        button3.setEnabled(false);
        button4.setEnabled(false);
        button5.setEnabled(false);
        button6.setEnabled(false);
        button7.setEnabled(false);
        button8.setEnabled(false);
        button9.setEnabled(false);
        button10.setEnabled(false);
        button11.setEnabled(false);
        button12.setEnabled(false);
        buttonNext.setEnabled(false);
        buttonPrev.setEnabled(false);
        buttonAm.setEnabled(false);
        buttonFm.setEnabled(false);
        guardar.setEnabled(false);
        rb1.setEnabled(false);
        rb2.setEnabled(false);
        rb3.setEnabled(false);
        rb4.setEnabled(false);
        rb5.setEnabled(false);
        rb6.setEnabled(false);
        rb7.setEnabled(false);
        rb8.setEnabled(false);
        rb9.setEnabled(false);
        rb10.setEnabled(false);
        rb11.setEnabled(false);
        rb12.setEnabled(false);
        
        
    }                                 

    private void buttonOnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        if(rb1.isEnabled()==false){
            button1.setEnabled(true);
            button2.setEnabled(true);
            button3.setEnabled(true);
            button4.setEnabled(true);
            button5.setEnabled(true);
            button6.setEnabled(true);
            button7.setEnabled(true);
            button8.setEnabled(true);
            button9.setEnabled(true);
            button10.setEnabled(true);
            button11.setEnabled(true);
            button12.setEnabled(true);
            buttonNext.setEnabled(true);
            buttonPrev.setEnabled(true);
            buttonAm.setEnabled(true);
            buttonFm.setEnabled(true);
            guardar.setEnabled(true);
            rb1.setEnabled(true);
            rb2.setEnabled(true);
            rb3.setEnabled(true);
            rb4.setEnabled(true);
            rb5.setEnabled(true);
            rb6.setEnabled(true);
            rb7.setEnabled(true);
            rb8.setEnabled(true);
            rb9.setEnabled(true);
            rb10.setEnabled(true);
            rb11.setEnabled(true);
            rb12.setEnabled(true);
            textEstacion.setText("87.9");
            textEmisora.setText("FM");
        } else {
            button1.setEnabled(false);
            button2.setEnabled(false);
            button3.setEnabled(false);
            button4.setEnabled(false);
            button5.setEnabled(false);
            button6.setEnabled(false);
            button7.setEnabled(false);
            button8.setEnabled(false);
            button9.setEnabled(false);
            button10.setEnabled(false);
            button11.setEnabled(false);
            button12.setEnabled(false);
            buttonNext.setEnabled(false);
            buttonPrev.setEnabled(false);
            buttonAm.setEnabled(false);
            buttonFm.setEnabled(false);
            guardar.setEnabled(false);
            rb1.setEnabled(false);
            rb2.setEnabled(false);
            rb3.setEnabled(false);
            rb4.setEnabled(false);
            rb5.setEnabled(false);
            rb6.setEnabled(false);
            rb7.setEnabled(false);
            rb8.setEnabled(false);
            rb9.setEnabled(false);
            rb10.setEnabled(false);
            rb11.setEnabled(false);
            rb12.setEnabled(false);
            
            
        }
    }                                        

    private void buttonAmActionPerformed(java.awt.event.ActionEvent evt) {                                         
      textEmisora.setText("AM");
       textEstacion.setText(String.valueOf(opera.Switch()));
        
        
    }                                        

    private void buttonFmActionPerformed(java.awt.event.ActionEvent evt) {                                         
       textEmisora.setText("FM");
       textEstacion.setText(String.valueOf(opera.Switch()));
    }                                        

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String emi = textEmisora.getText();
       
           textEstacion.setText(String.valueOf(opera.seleccionarFav(3)));
<<<<<<< HEAD
       
           
       
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
       
           textEstacion.setText(String.valueOf(opera.seleccionarFav(4)));
       
           
       
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        
           textEstacion.setText(String.valueOf(opera.seleccionarFav(5)));
       
        
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        
           textEstacion.setText(String.valueOf(opera.seleccionarFav(6)));
       
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        
           textEstacion.setText(String.valueOf(opera.seleccionarFav(7)));
       
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        
           textEstacion.setText(String.valueOf(opera.seleccionarFav(8)));
      
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        
           textEstacion.setText(String.valueOf(opera.seleccionarFav(9)));
      
    }//GEN-LAST:event_button9ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        
           textEstacion.setText(String.valueOf(opera.seleccionarFav(10)));
       
    }//GEN-LAST:event_button10ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
       
           textEstacion.setText(String.valueOf(opera.seleccionarFav(11)));
       
    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
       
           textEstacion.setText(String.valueOf(opera.seleccionarFav(12)));
      
    }//GEN-LAST:event_button12ActionPerformed
=======
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(15)));
       }
    }                                       

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(4)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(16)));
       }
    }                                       

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(5)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(17)));
       }
    }                                       

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(6)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(18)));
       }
    }                                       

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(7)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(19)));
       }
    }                                       

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(8)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(20)));
       }
    }                                       

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(9)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(21)));
       }
    }                                       

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(10)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(22)));
       }
    }                                        

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(11)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(23)));
       }
    }                                        

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String emi = textEmisora.getText();
       if(emi.equals("AM")){
           textEstacion.setText(String.valueOf(opera.seleccionarFav(12)));
       } else {
           textEstacion.setText(String.valueOf(opera.seleccionarFav(24)));
       }
    }                                        
>>>>>>> 8ba1c22f14cca9e9f754a029e09614693f887ac1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton button1;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button12;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAm;
    private javax.swing.JButton buttonFm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonOn;
    private javax.swing.JButton buttonPrev;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    private javax.swing.JTextField textEmisora;
    private javax.swing.JTextField textEstacion;
    // End of variables declaration                   
}
